### ISSUE TITLE
Error in Spec File

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-students/dynamic-orm-lab-v-000#38]
When the test suite is run, the following error occurs before each test output:
/home/ubuntu/workspace/orms-and-activerecord/orms/dynamic-orm-lab-v-000/spec/student_spec.rb:5: warning: already initialized constant DB
/home/ubuntu/workspace/orms-and-activerecord/orms/dynamic-orm-lab-v-000/spec/student_spec.rb:5: warning: previous definition of DB was here

Removing the redundant definition of the DB constant in the before block of the student_spec.rb file solves this problem.  I've opened a pull request containing a commit that solves the issue.

**Comment by aviflombaum** [comment]
@AnnJohn this needs to be moved to canonical.

**Comment by aviflombaum** [comment]
Moved

**Comment by AnnJohn** [comment]
thanks

**Comment by AnnJohn** [comment]
@DakotaLMartinez could you raise your pull request to the canonical lab as well- https://github.com/learn-co-curriculum/dynamic-orm-lab

thanks!
